name: parallel

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ['test:login', 'test:products']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install  # Install dependencies using npm

      - name: Run Cypress tests
        run: npm run ${{ matrix.script }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
